#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

echo -e "${LGREEN}--> Installing Atuin ...${WHITE}"
curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
echo "export ATUIN_SYNC_ADDRESS=https://atuin.jirm.cz" >> $HOME/.zshrc_local
echo '. "$HOME/.atuin/bin/env"' >> $HOME/.zshrc_local
echo 'eval "$(atuin init zsh)"' >> $HOME/.zshrc_local


