#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
  echo -e "${LYELLOW}--! This script needs to be run as root! Trying install with sudo...${WHITE}"
  exec sudo "$0" "$@"
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

# micro
echo -e "${LGREEN}--> Installing lf file manager ...${WHITE}"
app_exists "/usr/local/bin/lf"
lffile=$(basename $(curl -s https://api.github.com/repos/gokcehan/lf/releases | grep "browser_download_url.*lf-linux-amd64.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -n 1))
echo -e "${LGREEN}--> Downloading $lffile...${WHITE}"
curl -s https://api.github.com/repos/gokcehan/lf/releases | grep "browser_download_url.*lf-linux-amd64.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -n 1 | wget -q -O - -i - | tar -xzf - -C /usr/local/bin
cmd_check "lf download" $?
chmod +x /usr/local/bin/lf
/usr/local/bin/lf --version
install_check "lf" $?
