#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
  echo -e "${LYELLOW}--! This script needs to be run as root! Trying install with sudo...${WHITE}"
  exec sudo "$0" "$@"
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

resticScript="/usr/local/bin/restic-docker"

echo -e "${LGREEN}--> Installing Restic Docker script wrapper...${WHITE}"
app_exists $resticScript

echo -e "${LGREEN}--> Downloading restic-docker...${WHITE}"
curl -fsSL https://raw.githubusercontent.com/gjirm/various-projects/refs/heads/main/installers/scripts/restic-docker.sh > $resticScript

chmod +x $resticScript

resticConfig="/root/restic.env"
if [ ! -f $resticConfig ]
then
    echo -e "${LGREEN}--> Creating empty configuration $resticConfig ...${WHITE}"
cat <<EOF > $resticConfig
export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/backup-restic/my/server"
export AWS_ACCESS_KEY_ID="xxxx"
export AWS_SECRET_ACCESS_KEY="xxxx"
export RESTIC_PASSWORD="xxxx"
EOF
fi

$resticScript --help
install_check "restic-docker" $?
