# fly.toml file generated for jirm on 2022-02-17T12:13:43+01:00

app = "jirm"

[metrics]
  path = "/metrics"
  port = 9091

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 75
    type = "connections"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "10s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 6
    timeout = "2s"

    [services.http_checks.headers]
      Host = "jirm.cz"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
