#!/bin/bash

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
   echo -e "${LYELLOW}--! This script needs to be run as root!${WHITE}" 
   exit 1
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

# Function to install unzip on Debian-based distributions
install_unzip_debian() {
    apt-get update
    apt-get install -y unzip
}

# Function to install unzip on Red Hat-based distributions
install_unzip_redhat() {
    yum install -y unzip
}

# Function to install unzip on SUSE-based distributions
install_unzip_suse() {
    zypper install -y unzip
}

# Function to install unzip on Arch Linux
install_unzip_arch() {
    pacman -Syu --noconfirm unzip
}

# Function to install unzip on Alpine Linux
install_unzip_alpine() {
    apk add --no-cache unzip
}

# Function to install unzip on Fedora
install_unzip_fedora() {
    dnf install -y unzip
}

# Function to install unzip on FreeBSD
install_unzip_freebsd() {
    pkg install -y unzip
}

# Detect the Linux distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        ubuntu|debian)
            install_unzip_debian
            ;;
        centos|rhel)
            install_unzip_redhat
            ;;
        fedora)
            install_unzip_fedora
            ;;
        opensuse|suse)
            install_unzip_suse
            ;;
        arch)
            install_unzip_arch
            ;;
        alpine)
            install_unzip_alpine
            ;;
        *)
            echo "Unsupported Linux distribution: $ID"
            exit 1
            ;;
    esac
elif [ "$(uname)" = "FreeBSD" ]; then
    install_unzip_freebsd
else
    echo "Cannot detect the Linux distribution."
    exit 1
fi

# ethr
echo -e "${LGREEN}--> Installing Ethr ...${WHITE}"
app_exists "/usr/local/bin/ethr"
ethrfile=$(basename $(curl -s https://api.github.com/repos/microsoft/ethr/releases | grep "browser_download_url.*linux.zip" | cut -d : -f 2,3 | tr -d \" | head -n 1))
echo -e "${LGREEN}--> Downloading $ethrfile...${WHITE}"
mkdir micro-tmp
curl -s https://api.github.com/repos/microsoft/ethr/releases | grep "browser_download_url.*linux.zip"| cut -d : -f 2,3 | tr -d \" | head -n 1 | wget -q -O tmp.zip -i -
unzip tmp.zip -d /usr/local/bin/
cmd_check "Ethr download" $?
rm tmp.zip 
chmod +x /usr/local/bin/ethr
/usr/local/bin/ethr -h
#install_check "Ethr" $?
