#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
   echo -e "${LYELLOW}--! This script needs to be run as root!${WHITE}" 
   exit 1
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

# https://github.com/dundee/gdu
echo -e "${LGREEN}--> Installing gdu utility...${WHITE}"
app_exists "/usr/local/bin/gdu"
curl -sL https://github.com/dundee/gdu/releases/latest/download/gdu_linux_amd64.tgz | tar xz
cmd_check "gdu download" $?
chmod +x gdu_linux_amd64
mv gdu_linux_amd64 /usr/local/bin/gdu
/usr/local/bin/gdu --version
install_check "gdu" $?
