#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
   echo -e "${LYELLOW}--! This script needs to be run as root!${WHITE}" 
   exit 1
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

# ctop
echo -e "${LGREEN}--> Installing Helix editor...${WHITE}"
app_exists "/usr/local/bin/hx"
arch=$(uname -m)
if [[ "$arch" == "aarch64" ]]
then
  arch="arm64"
elif [[ "$arch" == "x86_64" ]]
then
  arch="x86_64"
fi
curl -s https://api.github.com/repos/helix-editor/helix/releases | grep "browser_download_url.*$arch-linux" | cut -d : -f 2,3 | tr -d \" | head -n 1 | wget -q -O - -i - | tar -xJf - --strip-components=1 -C /usr/local/bin
cmd_check "Helix download" $?
chmod +x /usr/local/bin/hx

/usr/local/bin/hx -V
install_check "Helix" $?
