#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
   echo -e "${LYELLOW}--! This script needs to be run as root!${WHITE}" 
   exit 1
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}

# mailsend-go
echo -e "${LGREEN}--> Installing mailsend-go...${WHITE}"
app_exists "/usr/local/bin/mailsend-go"
arch=$(uname -m)
if [[ "$arch" == "aarch64" ]]
then
  arch="linux-ARM"
elif [[ "$arch" == "x86_64" ]]
then
  arch="linux-64bit"
fi
mailfile=$(basename $(curl -s https://api.github.com/repos/muquit/mailsend-go/releases | grep "browser_download_url.*$arch.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -n 1))
echo -e "${LGREEN}--> Downloading $mailfile...${WHITE}"
mkdir mailsend-go-tmp
curl -s https://api.github.com/repos/muquit/mailsend-go/releases | grep "browser_download_url.*$arch.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -n 1 | wget -q -O - -i - | tar -xzf - --strip-components=1 -C ./mailsend-go-tmp
cmd_check "mailsend-go download" $?
mv "mailsend-go-tmp/mailsend-go" /usr/local/bin/mailsend-go
rm -rf "mailsend-go-tmp/"
chmod +x /usr/local/bin/mailsend-go
/usr/local/bin/mailsend-go -V
install_check "mailsend-go" $?
