#!/bin/bash

set -euo pipefail

LGREEN="\e[1;32m"
LYELLOW="\e[1;33m"
LBLUE="\e[1;34m"
LRED="\e[1;31m"
WHITE="\e[0m"

if [ $EUID -ne 0 ]
then
  echo -e "${LYELLOW}--! This script needs to be run as root! Trying install with sudo...${WHITE}"
  exec sudo "$0" "$@"
fi

app_exists () {
  if [ -f $1 ]
  then
    echo -e "${LBLUE}--> $1 already exists. Updating...${WHITE}"
    rm -f $1
  fi
}

install_check () {
  if [ $2 -eq 0 ]
  then
    echo -e "${LGREEN}--> $1 installation successfully completed!${WHITE}"
  else
    echo -e "${LRED}--X $1 installation failed. Exiting!${WHITE}"
    exit 1
  fi
}

cmd_check () {
  if [ $2 -ne 0 ]
  then
    echo -e "${LRED}--X $1 failed. Exiting!${WHITE}"
    exit 1
  fi
}


arch=$(uname -m)

if [[ "$arch" == "aarch64" ]]
then
  arch="arm64"
elif [[ "$arch" == "x86_64" ]]
then
  arch="amd64"
fi


# yq cli: https://github.com/smallyq/cli
echo -e "${LGREEN}--> Installing yq CLI utility...${WHITE}"
app_exists "/usr/local/bin/yq"

durl=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest | grep "browser_download_url.*linux_$arch.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -n 1)
file=$(basename $durl)

echo -e "${LGREEN}--> Downloading $file...${WHITE}"
curl -sL $durl | tar -xzf - -C /usr/local/bin --wildcards "*/yq_linux_$arch"
cmd_check "yq CLI download" $?
mv "/usr/local/bin/yq_linux_$arch" "/usr/local/bin/yq"
chmod +x /usr/local/bin/yq
chown root:root /usr/local/bin/yq
/usr/local/bin/yq --version
install_check "yq" $?

mkdir -p $HOME/.zsh_completions

/usr/local/bin/yq shell-completion zsh > $HOME/.zsh_completions/_yq
